[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
    "npm ci",
    "npx prisma generate"
]

[phases.build]
cmds = ["npm run build:server"]

[start]
cmd = "npm run start:server"

[variables]
NODE_ENV = "production"
PORT = "3001" 